networks:
  logging:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  pgdata:

services:
  loki:
    image: grafana/loki:3.4.4
    container_name: loki
    networks:
      - logging

  fluentd:
    build: ./logs
    container_name: fluentd
    environment:
      - LOKI_URL=http://loki:3100
    networks:
      logging:
        ipv4_address: 172.20.0.10
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/24224'"]
      interval: 5s
      timeout: 2s
      retries: 10

  grafana:
    image: grafana/grafana:11.5.0
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - logging
  
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - logging

  demo:
    image: python-app:hw-5
    container_name: demo
    environment:
      - USE_POSTGRES=true
      - POSTGRES_DB=demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    volumes:
      - ./static:/app/static:ro 
    ports:
      - "80:5000"
    networks:
      - logging
    logging:
      driver: fluentd
      options:
        fluentd-address: 172.20.0.10:24224
        tag: docker.demo
    depends_on:
      fluentd:
        condition: service_healthy
      grafana:
        condition: service_started
      loki:
        condition: service_started
