apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-static-pvc
  namespace: demo
spec:
  storageClassName: demo-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
