apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-static-pv
  namespace: demo
spec:
  storageClassName: demo-static
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ostap/devops_course/17-Pazynuyk-Ostap/static
