apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: demo
  labels:
    app: demo-app
  annotations:
    promtail.io/scrape: "true"
    promtail.io/path: "/var/log/containers/*${POD_NAME}*.log"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-container
        image: opazyniuk/python-app:hw-8
        ports:
        - containerPort: 5000
        env:
        - name: BACKGROUND_COLOR
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKGROUND_COLOR
        - name: FIB_NUMBER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FIB_NUMBER
        - name: USE_POSTGRES
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USE_POSTGRES
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: POSTGRES_PASSWORD
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
          - name: static
            mountPath: /app/static
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
        - name: static
          persistentVolumeClaim:
            claimName: demo-static-pvc

